"""empty message

Revision ID: 85ed831fe056
Revises: 
Create Date: 2021-06-03 16:36:53.681977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85ed831fe056'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queuemanager',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=256), nullable=True),
    sa.Column('link_id', sa.String(length=256), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('doc_url', sa.String(length=256), nullable=True),
    sa.Column('current_status', sa.String(length=32), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('tries', sa.Integer(), nullable=True),
    sa.Column('url_expires', sa.BigInteger(), nullable=True),
    sa.Column('doc_name', sa.Text(), nullable=True),
    sa.Column('long_doc_url', sa.Text(), nullable=True),
    sa.Column('pdf_version', sa.Integer(), nullable=True),
    sa.Column('error_encountered', sa.String(), nullable=True),
    sa.Column('task_completed', sa.Boolean(), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('queuemanagerbackup',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.String(length=256), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('temp_req',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=256), nullable=True),
    sa.Column('form_id', sa.String(length=256), nullable=True),
    sa.Column('user_name', sa.String(length=256), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('outputtable',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('pdftable_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.String(length=256), nullable=True),
    sa.Column('link_id', sa.String(length=256), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('doc_url', sa.String(length=128), nullable=True),
    sa.Column('url_expires', sa.BigInteger(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('doc_name', sa.Text(), nullable=True),
    sa.Column('pdf_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pdftable_id'], ['queuemanager.unique_id'], ),
    sa.PrimaryKeyConstraint('unique_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outputtable')
    op.drop_table('temp_req')
    op.drop_table('queuemanagerbackup')
    op.drop_table('queuemanager')
    # ### end Alembic commands ###
