"""empty message

Revision ID: c3721bca540b
Revises: 
Create Date: 2020-05-14 13:32:00.396334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3721bca540b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outputtable',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=256), nullable=True),
    sa.Column('link_id', sa.String(length=256), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('doc_url', sa.String(length=128), nullable=True),
    sa.Column('url_expires', sa.BigInteger(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('doc_name', sa.Text(), nullable=True),
    sa.Column('pdf_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('queuemanager',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=256), nullable=True),
    sa.Column('link_id', sa.String(length=256), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('doc_url', sa.String(length=256), nullable=True),
    sa.Column('current_status', sa.String(length=32), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('tries', sa.Integer(), nullable=True),
    sa.Column('url_expires', sa.BigInteger(), nullable=True),
    sa.Column('doc_name', sa.Text(), nullable=True),
    sa.Column('pdf_version', sa.Integer(), nullable=True),
    sa.Column('error_encountered', sa.String(), nullable=True),
    sa.Column('task_completed', sa.Boolean(), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('temp_req',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.String(length=256), nullable=True),
    sa.Column('form_id', sa.String(length=256), nullable=True),
    sa.Column('user_name', sa.String(length=256), nullable=True),
    sa.Column('is_update', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_req')
    op.drop_table('queuemanager')
    op.drop_table('outputtable')
    # ### end Alembic commands ###
