"""empty message

Revision ID: cf6c5b9c87d2
Revises: 1eaba328ce8e
Create Date: 2020-06-12 11:27:07.958168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6c5b9c87d2'
down_revision = '1eaba328ce8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queuemanager', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queuemanager', 'is_delete')
    # ### end Alembic commands ###
