# Generated by Django 3.2.12 on 2022-03-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_auto_20220224_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='plugin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
