# Generated by Django 3.2.12 on 2022-02-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_alter_genericconfig_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericconfig',
            old_name='shotener_ref',
            new_name='shortener_ref',
        ),
    ]
