# Generated by Django 3.2.8 on 2021-10-31 20:09

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_rename_school_audit_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericConfig',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('data', fernet_fields.fields.EncryptedTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pdf',
            name='config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.genericconfig'),
        ),
    ]
