# Generated by Django 3.2.12 on 2022-02-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_rename_shotener_ref_genericconfig_shortener_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericconfig',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
