# Generated by Django 3.2.12 on 2022-09-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_auto_20220301_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericconfig',
            name='uploader_ref',
            field=models.CharField(blank=True, choices=[('minio', 'Minio'), ('generic_minio', 'Generic Minio')], max_length=20, null=True),
        ),
    ]
