# Generated by Django 3.2.8 on 2021-11-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_auto_20211101_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericconfig',
            name='max_concurrency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='genericconfig',
            name='retries',
            field=models.IntegerField(default=0),
        ),
    ]
