# Generated by Django 3.2.8 on 2021-10-30 06:14

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), null=True, size=None)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('url_meta', models.JSONField()),
                ('url_expiry', models.DateTimeField(null=True)),
                ('short_url', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Processing', 'Processing'), ('Failed', 'Failed'), ('Complete', 'Complete'), ('Error', 'Error')], default='Queued', max_length=20)),
                ('step', models.CharField(choices=[('Not Started', 'Not Started'), ('Data Fetching', 'Data Fetching'), ('Mapping Fetching', 'Mapping Fetching'), ('Template Processing', 'Template Processing'), ('PDF Building', 'PDF Building'), ('Uploading', 'Uploading'), ('URL Shortening', 'URL Shortening'), ('Deleted From Drive', 'Deleted From Drive')], default='Not Started', max_length=30)),
                ('tries', models.IntegerField(default=0)),
                ('version', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Processing', 'Processing'), ('Failed', 'Failed'), ('Complete', 'Complete'), ('Error', 'Error'), ('None', 'None')], default='None', max_length=20)),
                ('stacktrace', models.JSONField(null=True)),
                ('school', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.pdf')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
